import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@repo/ui/utils';
import '@repo/ui/global.css';

export const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'flex min-h-svh antialiased')}>{children}</body>
    </html>
  );
}
