import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '~/components/utils';
import './global.scss';

export const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Project CRXup',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" data-theme="dark">
      <body className={cn(inter.className, 'flex min-h-svh antialiased')}>{children}</body>
    </html>
  );
}
